import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f9fa",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingTop: 40,
    },
    backButton: {
        position: "absolute",
        top: 20,
        left: 20,
        padding: 10,
    },
    title: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 20,
        color: "#333",
    },
    profileImage: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 2,
        borderColor: "#007bff",
        marginBottom: 10,
    },
    imageText: {
        fontSize: 14,
        color: "#007bff",
        textDecorationLine: "underline",
        marginBottom: 15,
    },
    input: {
        width: "100%",
        height: 50,
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingHorizontal: 15,
        fontSize: 16,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    datePicker: {
        width: "100%",
        height: 50,
        justifyContent: "center",
        backgroundColor: "#fff",
        borderRadius: 8,
        paddingHorizontal: 15,
        borderWidth: 1,
        borderColor: "#ddd",
        marginBottom: 10,
    },
    dateText: {
        fontSize: 16,
        color: "#333",
    },
    button: {
        backgroundColor: "#007bff",
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 8,
        marginTop: 10,
        width: "100%",
        alignItems: "center",
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalCloseButton: {
        backgroundColor: "#fff",
        padding: 10,
        borderRadius: 5,
        marginTop: 10,
    },
});
